server:
  port: 8082

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://mysql:3306/emp?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

  # redis:
  #   host: host.docker.internal
  #   port: 6379
  #   timeout: 60000

logging:
  level:
    root: INFO
    vn.vku.booking: DEBUG
    org.hibernate.SQL: DEBUG