openapi: 3.0.3
info:
  title: Appointment API
  version: 1.0.0

paths:
  /api/v1/appointments/slots/book:
    post:
      summary: Create a new appointment slot booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                  format: int64
                service_id:
                  type: integer
                  format: int64
                service_name:
                  type: string
                employee_id:
                  type: integer
                  format: int64
                employee_name:
                  type: string
                time:
                  type: string
                  format: date-time
                notes:
                  type: string
              required:
                - customer_id
                - service_id
                - employee_id
                - time
      responses:
        '200':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer_id:
                    type: integer
                    format: int64
                  appointment_id:
                    type: integer
                    format: int64
                  service_id:
                    type: integer
                    format: int64
                  service_name:
                    type: string
                  employee_id:
                    type: integer
                    format: int64
                  employee_name:
                    type: string
                  time:
                    type: string
                    format: date-time
                  status:
                    type: string
                  notes:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '409':
          description: Conflict - appointment could not be created
