server:
  port: 8083

spring:
  application:
    name: scheduling-service
  datasource:
    url: jdbc:postgresql://postgres:5433/scheduling_db
    username: appointment
    password: hunghv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  services:
    scheduling:
       url: http://scheduling-service:8083/api/v1/schedule
    employee:
       url: http://employee-service:8082/api/v1/employees

logging:
  level:
    root: INFO
    vn.vku.booking: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics