# Stage 1: Build JAR
FROM maven:3.9.6-eclipse-temurin-17-alpine AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:resolve

COPY src ./src

RUN mvn package -DskipTests

# Stage 2: Run JAR
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=builder /app/target/notification-service-*.jar app.jar

EXPOSE 8084

ENTRYPOINT ["java", "-jar", "app.jar"]

