server:
  port: 8084

spring:
  application:
    name: notification_service

  autoconfigure:
    exclude: 
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  rabbitmq:
    host: rabbitmq
    port: 5672

  mail:
    host: smtp.gmail.com
    port: 587
    username: leduclong0604@gmail.com
    password: hhnlnelnzvbxjyjr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

