version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-emp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emp
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: redis-emp
    ports:
      - "6379:6379"

  employee-service:
    build: .
    container_name: employee-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/emp?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
